### ISSUE TITLE
Employee

### ISSUE THREAD

**Issue by Th3Scorpio** [castlamp/zenbership#107]
When I create an Employee, and login with the account, the employee can not change or update his/her own detail?

**Comment by jbelelieu** [comment]
The employee system needs a complete overhaul, I am aware of this and many other related issues.

**Comment by Th3Scorpio** [comment]
Hi

Tx
I managed to do a workaround

I created another page from employees and then created an extra permission group.
Then changed the $permission setting in the new page to have access to their own account
Just removed some of the fields in the extra page to prevent them changing their own permissions ect


Tx for the feedback


Regards

 André Esterhuizen
Phone:+27 11 412 2837 |Fax: +27 86 616 2747 | E-mail: andre@technowiz.co.za
"Nothing To Do With Magic, Everything To Do With Information Technology"
[Description: BBtr][Description: bbCA] [Description: MCSE-col.jpg]
