### ISSUE TITLE
Failed: could not find driver

### ISSUE THREAD

**Issue by wandyirawan** [castlamp/zenbership#119]
Hi, please help 
at setup,  write permistion all has green. but when im test connection show like a title.
at linux manjaro at localhost with php 7

this zenbership must work at php 5.6? 

Thank You

**Comment by dameon6** [comment]
Anyway you can provide a screenshot of the error?  I'm running Zenbership on php 7.0.24, but the documentation states its compatible with 5.3 up.

**Comment by wandyirawan** [comment]
![this is prove](https://user-images.githubusercontent.com/10525732/31478322-c19edf48-af39-11e7-9465-a243e7eef259.PNG)

**Comment by dameon6** [comment]
Check your php.ini install and make sure the pdo extension is enabled:
extension=php_pdo_mysql.dll

If not you can install it with:
    PHP5: sudo apt-get install php5-mysql
    PHP7: sudo apt-get install php7.0-mysql

After install, restart the server and try again, see if that fixes your driver issue.

**Comment by wandyirawan** [comment]
done.. i got this after re install my vbox to ubuntu.. 
thanks for all help.
