### ISSUE TITLE
Cant add "Employees"

### ISSUE THREAD

**Issue by direktorn** [castlamp/zenbership#131]
Hi,
I've finally managed to get zenbership installed, had to tweak mysql a bit (lot) and change most permissions to 777. 

However adding new employees (apart from the "admin") is not possible. 

The interface just reloads to my own admin and the "console" trows an error: 
1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0,' at line 1

mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

Running AWS Linux.

**Comment by dameon6** [comment]
This is confirmed, only Admin is the option.  Any other options will add a zero error to mysql.

**Comment by ioamnesia** [comment]
Dameon, could you clarify? What do you mean "only Admin is the option"?

**Comment by steviobee** [comment]
I have same issue, although I get the form in create employee, there is no field for first name, etc plus only one option is admin?

**Comment by dameon6** [comment]
It looks like its hardcoded for admin only, I am going to experiment with it and see if I can add a new group.

**Comment by steviobee** [comment]
Weirdly, I had this sorted on the old 107 version, but have lost the add employee function now

**Comment by jbelelieu** [comment]
The employee system is a little bit of a mess and has been temporarily "deactivated" (meaning you can only create admins for the time being) until a better solution can be put in place.
