### ISSUE TITLE
Cannot test through Stripe

### ISSUE THREAD

**Issue by bdruth** [castlamp/zenbership#133]
I've setup a Stripe account and entered the secret + publishable keys into the credentials for the gateway. Unfortunately, the Zenbership + Stripe integration appears to be broken when processing test transactions. Specifically, Stripe requires a token to be passed through:
>Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing. (Code: invalid_request_error).
So, instead of passing, e.g. ``4242424242424242`` for a Visa, you should pass ``tok_visa``. But, that violates the CC# field's validation, so - you can't.

Not sure if this is a recent change in the Stripe API or what, but it seems like it's something that needs to get fixed?

Thanks!

**Comment by bdruth** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/444571/33091913-1d6cd6a6-cebe-11e7-8430-58dfddd19af2.png">
Required if you want to use Stripe w/ Zenbership (testing or otherwise), it seems.

**Comment by jbelelieu** [comment]
I am not experiencing these issues nor have I heard of a need to tick that checkbox.

Are you sending over https?

**Comment by jglaine** [comment]
Confirmed for me as well : stripe needs to be set to "unsafe" to receive credit card info and tokenize it.

**Comment by bdruth** [comment]
I have opted to use a different membership system that integrates more cleanly with Stripe.
