### ISSUE TITLE
installation issues 115 - help

### ISSUE THREAD

**Issue by steviobee** [castlamp/zenbership#135]
Can someone assist, 

I have installed Zenbership using Softaculous onto the cPanel (version 68.0 (build 16)) - php 5.4.34, mySQL 5.5.58-cll, on linux. But the version they install is only 107.
It all works until I try to upgrade to 115, I have edited 115.php and the database gets updated okay with all the updates, but after I FTP the physical files and adjust the permissions I get a 500 error.
I have tried starting from scratch too, by installing 115 straight up but still it doesn't work.
I have tried Filezilla on PC and MAC.
I have no worries about saving files as I haven't set it all up yet, so am not worried about data loss but would like the latest version before I set it up.
I have contacted Castlamp but no reply as yet, can anyone help, I can pay but would like to get this setup for our local club ASAP.

**Comment by steviobee** [comment]
@jbelelieu are you able to assist?

**Comment by steviobee** [comment]
I have managed to get somewhere, as ETWebs suggested - I uploaded the zip file and uncompressed in the cPanel.
Working now.

**Comment by dameon6** [comment]
This sounds like it was a permissions issue, when you uploaded them manually the correct permissions were not assigned, unzipping using cpanel would provide web server permissions.

**Comment by steviobee** [comment]
Strange as I checked every permission as in instructions from both cPanel file manager and FileZilla.
My issue now is the version number, I have installed 115 from website but app shows 111?

**Comment by dameon6** [comment]
Mine does as well, its probably just a typo in the latest update.  I will try to locate it tonight.

**Comment by steviobee** [comment]
Great thanks, let me know, I'm thinking I may have somehow installed the wrong one anyway??

**Comment by dameon6** [comment]
It appears to be a typo in the SQL Database, the database incorrectly references the older version.  If you compare the 115 files to the files in the install, they match.

**Comment by jbelelieu** [comment]
So the version being displayed might not reflect the actual version you are running. I recently updated the updater to use the display version (v115) after installation.

I'm talking to the Softaculous people to ensure that everything is good to go on this front. Closing this for now though.
