### ISSUE TITLE
Membership Numbers Configuration

### ISSUE THREAD

**Issue by steviobee** [castlamp/zenbership#136]
Can members’ ID number be predefined? Even with inputting nnn it comes up with random numbers?
i.e.  our members already have their numbers 1, 2, 3, etc and new members to Zenbership site should be sequential from then on, 61,62,63, etc

We have issued members cards and it would be nice to keep same numbers.

**Comment by dameon6** [comment]
This is the code that appears to trigger the ID format:
    $cid             = generate_id($db->get_option('member_id_format'));

Its located in cp-includes > Pages > member-add.php.

I will see if I can hunt down the function itself tonight.

**Comment by dameon6** [comment]
Ok, so the code you need to edit is in admin > cp-classes > universal.class.php around line 312.  

Here is the bad news, the formatting is hard coded.  You are better off generating your own function in this file to do what you want.  It might be easier to just change the field in SQL to auto increment and disable the code by commenting it out in the member function.

Either this or you'll need to set it manually each time.

**Comment by jbelelieu** [comment]
You can customize the format but you cannot currently make it sequential without altering core code or using a custom PHP hook to overwrite the user's ID after registration.

There are a lot of consequences to updating an ID without making sure it propagates throughout the database (unfortunately the program doesn't use foreign keys so making these updates seamless is less than easy.)

**Comment by steviobee** [comment]
I have added a custom field %membership_number% to a few html pages now. We will add our numbers in ourselves manually.

**Comment by dameon6** [comment]
I did this the same way, along with all of my other custom fields.  The main reason being I don't allow open registration anyway, so each member needs to be manually approved once.  Just as easy to add the information then and keep the unique ID Zen assigns.
