### ISSUE TITLE
displaying custom fields as read only

### ISSUE THREAD

**Issue by steviobee** [castlamp/zenbership#137]
Can some of the custom fields be displayed to the user as read only - like original join date, member number, etc?

**Comment by dameon6** [comment]
Yes, it can be done through creating a fieldset that is accessible to members and contains the fields that you want to display.

**Comment by steviobee** [comment]
Thanks Dameon - Is there a way to prevent this data field from being changed though? i.e. visible but unable to change it.

**Comment by dameon6** [comment]
Members shouldn't be able to change it, I will experiment with it and let you know.

**Comment by steviobee** [comment]
I found this in the admin panel, via 'Members' - 'Options' 

_Additional Member Filters_

_Display additional member filters for all employees? Input as a CSV of field IDs._

Not sure what thats for?

**Comment by jbelelieu** [comment]
By "user" are you referring to members or backend (admin dashboard) users?

**Comment by steviobee** [comment]
Member user from frontend

**Comment by jbelelieu** [comment]
You can print any field you want on a page using caller tags:
http://documentation.zenbership.com/Integration/Caller-Tags

That includes all templates and custom pages (assuming the user is logged in).

That would be the best way to display fields without allowing users to update them directly.
