### ISSUE TITLE
Subscription/Feature Product - sometimes shows up?

### ISSUE THREAD

**Issue by steviobee** [castlamp/zenbership#142]
I have been a bit confused with the whole subscription product thing. I have setup new members to fill out a form from the home page and then go through to join, but I also added a subscription product to the same membership before I realised I could not add the form to that so I removed it.
I now can't see the subscription product in the products section in admin panel, yet when I click on the shop when not signed in to members I can see the product but only sometimes?
https://members.vespaclubsydney.com.au/catalog.php
See above, it seems to appear then after a few refreshes it goes but then comes back again. Strange!
I have tried various different browsers and clearing the cache, etc... sometimes it take a few goes to show back up.
If you click it when it is there, it shows a 'The product that you are trying to access could not be found or is not accessible at this time.' error?

**Comment by dameon6** [comment]
For me it doesn't show at all.   Browser is bugged maybe?  I tried refreshing a bunch of times.

**Comment by steviobee** [comment]
It is showing here as a featured product? I cannot get rid, been trying incognito in chrome, Iexplorer and Edge?
Sometimes 5 or so refreshes

**Comment by KaiBuskirk** [comment]
Steve, 
Did you try it on another system and browser...
i usually test across 9 devices 
desktop, mobile
Mac, Window, iOS,Windows..
just to try to see how jo public is seeing ...
but from what i can see your ok?
#GhostInTheMachine

**Comment by steviobee** [comment]
![zenbership_product_still_displayed_sometimes](https://user-images.githubusercontent.com/33817621/33693920-887585be-db49-11e7-9dfa-382eaeb25101.jpg)

I have tried numerous machines, do you guys never see the product in the 'Featured Product' area as in image attached? It comes up randomly after a few refreshes for me everywhere?

**Comment by steviobee** [comment]
This may be related but I am unable to see the subscription product in the admin area, yet I am still able to sign up via the members home page with the members form and correct payment choice.

Where can I change the price of sign up to members area if no subscription product exists?
Am I missing something?

**Comment by steviobee** [comment]
AHHHH! - found it, it was a set to 'Featured Product' but also set to bookeeping only in the options. It does not show up in the Shop or Products area but is found via the link from an existing subscriber.
