### ISSUE TITLE
Editing a custom field from the admin panel

### ISSUE THREAD

**Issue by steviobee** [castlamp/zenbership#143]
Once a member has subscribed, we need to go into their settings in the admin panel and add in a member number that we have a custom field created for. I cannot find a way to edit a custom field?

**Comment by steviobee** [comment]
my workaround is to edit the custom field via the cPanel in phpMyAdmin and editing the `ppSD_member_data` in the database but I'd prefer a front end way of changing this like any other field?

**Comment by dameon6** [comment]
Make sure the fieldset's is in included the scope for that field on the form you want to edit it on.

For example, if you want it to show on "Member Edit" make sure you check the scope checkbox.  This will make the field editable when you click on the member as an admin.

**Comment by steviobee** [comment]
@dameon6 thanks for that - obvious now, I'll close this issue.
