### ISSUE TITLE
Unable to export the members list

### ISSUE THREAD

**Issue by steviobee** [castlamp/zenbership#149]
![image](https://user-images.githubusercontent.com/33817621/34194135-5413358e-e5ab-11e7-9cbc-df37fa5b7d34.png)

I goto 'Members' then 'Export' which gives me this:

![image](https://user-images.githubusercontent.com/33817621/34194169-7475fc3a-e5ab-11e7-8bac-4f94a5843502.png)
Clicking 'Export' just returns me to the members list again?
There is only one option 'Delimiter type'

This used to work in 107 I'm sure?

**Comment by dameon6** [comment]
Confirmed for Chrome and Firefox, however, Microsoft Edge Works.

**Comment by steviobee** [comment]
Thanks, MS Edge does work.

**Comment by steviobee** [comment]
Will close issue as other browser option is working.
