### ISSUE TITLE
Fix for automated email campaings

### ISSUE THREAD

**Issue by worraps** [castlamp/zenbership#180]
Building of criteria query fails with invalid field in select list.  I imagine most of the contacts and members fields were at some point moved to the *_data version of the table.  Other bugs seem to reference fields that are no longer in main table but in the *_data table.. just a guess though.

Anyway to fix it...
v115
File: admin/cp-classes/criteria.class.php
Line 182
Change **ppSD_member_data.email** to **ppSD_members.email**
Line 192
Change **ppSD_contact_data.email** to **ppSD_contacts.email**

**Comment by jbelelieu** [comment]
This will be patched in the next version - thank you!
