### ISSUE TITLE
Mcrypt depreciated in PHP 7, will zenbership update soon?

### ISSUE THREAD

**Issue by jamminjames** [castlamp/zenbership#181]
Will the dependency on mcrypt be changed soon, to defuse or RNCryptor? Mcrypt has been abandonware for nearly a decade now. It has been deprecated and will be removed in PHP 7.2, from what I've read.

I am running PHP 7.0 on a Centos 7 server with Nginx. We have mcrypt installed, but the zenbership setup highlights it in red, indicating it's not installed. Same with GD, which is also installed.

Can one of these other solutions be used by customizing zenbership somehow? Or, how can I get zenbership to recognize the mcrypt and GD we have installed?

**Comment by jbelelieu** [comment]
Development on Zenbership has been temporarily stopped for the foreseeable future. No new updates should be expected this year.
