### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by pwillip108** [castlamp/zenbership#223]
I know there is no current support, but is there anywhere I can find a copy of the documentation?

**Comment by taz4535** [comment]
While the website was up and running it was paired with very good build
documentation. I never saved it, but hopefully someone did, otherwise
you're back to Jon who created it.

**Comment by mwilliams4nc** [comment]
I would love to see that documentation.
Wouldn't Jon be able to post that?

**Comment by jbelelieu** [comment]
I wish i could. The computer it was built on is dead and the hosting it was built on (as well as the domain itself) was lost to a hacker presumably. I can’t find a backup of the docs anywhere but I am trying to track it down I promise. Sorry everyone, it’s been a rough go the last couple months trying to recover all of this.

**Comment by mwilliams4nc** [comment]
normally there is a more complete setup admin area, what would be the first steps that I should take after installation? Looks like great software but without the documentation, a little guidance would be helpful

**Comment by jbelelieu** [comment]
The best I can do for now until I sort everything out is direct you to this:
https://web.archive.org/web/20181221174926/http://documentation.zenbership.com/

**Comment by pwillip108** [comment]
Thanks!!! This is perfect to get started….

**Comment by mwilliams4nc** [comment]
Yes, looks very promising!

**Comment by jbelelieu** [comment]
Documentation has been recovered to: http://docs.zenbership.org/

**Comment by pwillip108** [comment]
Thank you!  I really appreciate your effort on a deprecated project.
