### ISSUE TITLE
I just installed the software, lost

### ISSUE THREAD

**Issue by mwilliams4nc** [castlamp/zenbership#224]
I just installed the software and it is up and running but when I try to register as a new member there all it shows is registration options and there are none there.

Can anyone point me in the right direction?

**Comment by taz4535** [comment]
Screenshot?

**Comment by jbelelieu** [comment]
When creating a reg page there should be an option to change the visibility

**Comment by mwilliams4nc** [comment]
[image: image.png]

**Comment by mwilliams4nc** [comment]
where do I create the reg page?
ACCOUNTS
CONTACTS
MEMBERS
SHOP
EVENTS
CONTENT
MARKETING
INTEGRATE

**Comment by jbelelieu** [comment]
Integrate

**Comment by mwilliams4nc** [comment]
Plugins»
Hooks»
TEMPLATES
HTML Templates»
E-Mail Templates»
FORMS
Forms»
Fields
Fieldsets
ADMINISTRATIVE TASKS
Options
Language & Errors
Database

**Comment by mwilliams4nc** [comment]
Please select your desired registration option from the list below.
And below is nothing.

When I try and create a form it never saves.

**Comment by taz4535** [comment]
![image](https://user-images.githubusercontent.com/30848350/76719073-c831a300-678c-11ea-80ff-0d77baa9ea65.png)
The above is where you setup the below:
![image](https://user-images.githubusercontent.com/30848350/76719088-d41d6500-678c-11ea-963a-6e758267ca4e.png)

**Comment by mwilliams4nc** [comment]
how about a free registration

**Comment by jbelelieu** [comment]
When you click on "Create a Form" it will provide you with multiple options, including free registration forms.

**Comment by mwilliams4nc** [comment]
Where does the signed-in user show on the page? 

Also do you need hosting for the site moving forward?

**Comment by jbelelieu** [comment]
I don't follow either question, apologies.

Which signed in user and which page?

Also can you clarify what you mean by "hosting for the site" -- which site?

**Comment by mwilliams4nc** [comment]
Q1:
Normally when you are signed in and working (like me as administrator) you see a link to your profile to know who is signed in somewhere on the page. Usually with normal UI its on the top right of the page.

Q2: 
Do you need hosting to get the docs actually published rather than an archive site?
Do you need hosting to get the hacked site back up and running?
I have hosting to offer, no cost

**Comment by jbelelieu** [comment]
Q1: The program has two separate "secure" areas: the member frontend and the admin frontend. In both cased once you're logged in the user data will appear on those pages. https://web.archive.org/web/20190126012818/http://documentation.zenbership.com/Home/List-of-Common-URLs

Q2: I'm fine hosting wise thank you though. You can see the site progressing at zenbership.org. I'm working on recovering the docs but they were created using a database-driven tool from 7 years ago, so it's been hard to find a backup database as well as a copy of that tool again. Once I manage to do that I will put them up on the zenbership.org site.

**Comment by mwilliams4nc** [comment]
So once logged in as the admin there is no visible link on any page that says "Admin" that I can click on and get to my "admin" profile?

**Comment by jbelelieu** [comment]
There is in the top right. It says "Welcome ...".

**Comment by mwilliams4nc** [comment]
ok, so that is limited to basic stuff password, name, signature. 
Where can the individual user set his own timezone and other settings?

**Comment by jbelelieu** [comment]
Please take a look at the docs:
http://docs.zenbership.org/
