### ISSUE TITLE
Pending Approval members are able to enter members' area

### ISSUE THREAD

**Issue by elsatch** [castlamp/zenbership#26]
We've been testing several scenarios and end up having memberships manually approved by admins. As we were testing with new users, we discovered that once the checkout process finishes users are presented with a link to the Members' area. 

To our surprise member whose status is Pending Admin Approval are able to enter the Members' area. I assume pending members should not be able to enter this area until finally approved.

**Comment by jbelelieu** [comment]
Are you 100% certain they are status "pending"? The login.php code throws an error code "L010" if the status is not active. How are your members registering? Is this from a cart purchase or from a registration form?

**Comment by elsatch** [comment]
Registration originated from a registration form. Users had to get a invitation code to enter the form. After finishing the process, we got the link to the Member's area.

I'm sorry I can't offer any additional information as we are moving to another solution.

Thanks for your response and sorry for late response.

**Comment by Th3Scorpio** [comment]
Hi
I picked this up as well
Im using registration form
When confirmation complete, the member can access the member area without login
I think something to do with the tracking and caching of the registration process
I changed the confirmation page in the template html editor.
It destroy all session information and redirect to login page
it solved  the problem
