### ISSUE TITLE
Misreporting of "Your subscription will renew in x days"

### ISSUE THREAD

**Issue by hailthemelody** [castlamp/zenbership#31]
Hi,

I'm currently testing out a daily renewal, and although it's successfully charging daily and listing the following day as the next renewal in the body of the text, the email subject and "title" list the next renewal as being in 7 days.

Any ideas? I'm going to look into the issue and make a pull request if I can fix it.

**edit:** Seems that the logic doesn't calculate if the next renewal date is before the next alert-before renewal date

**Comment by jbelelieu** [comment]
This comes from the fact that the email is generating the subject based on the option, not the subscription itself. In order words, if your subscription options are set up to notify a user "7 days" before a subscription renews, the program will use that as the basis for the subject line. The subject line should technically read "Your subscription will renew within 7 days", which is something you can manually update from the "Integration > Email Templates" section of the control panel.

I'll make a note of this and hopefully re-work the issue in the v109.
