### ISSUE TITLE
Cannot login and SQL error on fresh install

### ISSUE THREAD

**Issue by jackmcgary** [castlamp/zenbership#36]
I tried to install on Ubuntu 16, everything fresh. I complete the setup process successfully then I go to login here:

/admin/login.php?n=eas4

When I enter the admin user/password is just shows a red bar and I cannot login. If I go to the homepage it just shows this error message:

Invalid query ( SELECT * FROM `ppSD_widgets` WHERE `id`=? LIMIT 1 ): 42S02---1146---Table 'zen.ppSD_widgets' doesn't exist--->site_topbar

I see all of the other "ppSD" tables but not that widgets table. I installed it my git cloning the master branch. Thanks much for any help.

**Comment by jbelelieu** [comment]
This is odd. You can find the SQL command for creating the table within the "setup/mysql/create.php" file. If you have access to phpMyAdmin or a similar tool you can run it manually. I'll look into why it may not have been created during setup as soon as I can.

**Comment by jbelelieu** [comment]
```
CREATE TABLE IF NOT EXISTS `ppSD_widgets` (
  `id` varchar(75),
  `name` varchar(45),
  `type` enum('plugin','menu','html','code','upload_list'),
  `menu_type` enum('horizontal','vertical'),
  `content` longtext,
  `active` tinyint(1),
  `add_class` varchar(50),
  `author` VARCHAR( 35 ) ,
  `author_url` VARCHAR( 120 ) ,
  `author_twitter` VARCHAR( 120 ) ,
  `version` VARCHAR( 6 ) ,
  `installed` DATETIME DEFAULT '0000-00-00 00:00:00',
  `original_creator` VARCHAR( 40 ),
  `original_creator_url` VARCHAR( 120 ) ,
  `description` TEXT,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by jackmcgary** [comment]
Thanks, figured it out. When I ran that insert it gave me these:
ERROR 1067 (42000): Invalid default value for 'installed'
The server had safe mode enabled with SQL Mode - NO_ZERO_DATE. Removed that and everything worked fine.
