### ISSUE TITLE
Required Email Field

### ISSUE THREAD

**Issue by mikeamcbrien** [castlamp/zenbership#37]
When sending out a new email to a contact, the Subject is NOT a required field.  without it many of my emails are being sent straight to 'junk' in various email clients. 

Please make this a required field.

On a side note, is there any plans to keep the entire email conversation within zenbership, so If someone responds to an email is tracked in the Zenbership system.

**Comment by jbelelieu** [comment]
We will take your suggestion into consideration moving forward. Thank you!

Yes, an email piping module is being created for v109 beta.

**Comment by mikeamcbrien** [comment]
Thanks, As I am working through the workflow for v109 I am finding other errors or suggestions, would you like me to continue to report those? Do you have any need for additional pre-release testing?

**Comment by mikeamcbrien** [comment]
Do you want me to create issues for suggetsions? Do you have a master 'to-do' list of things that have already been identified? Do you have any other non-public builds that have fixes addressed?  Some fixes are small styling and css issues that are likely fixed globally with small changes.
