### ISSUE TITLE
How to add employee?

### ISSUE THREAD

**Issue by ETWebs** [castlamp/zenbership#43]
I actually want to add an administrator, but apparently you make an employee which you make an administrator.
But the docs say to click on "Employee's" in the top bar, but I don't have that option??
BTW, This is a new fresh install.

**Comment by jbelelieu** [comment]
It is in the black top bar in the top right hand corner of the administrative dashboard. The only reason you might not see it is if you are logged in as an employee who is not an admin.

**Comment by ETWebs** [comment]
I'm sure you have better things to do than answer stupid questions from silly people.
But, then again.... I'll probably have some more ... <feeling foolish>
