### ISSUE TITLE
Error when listing Fieldsets in version 110b

### ISSUE THREAD

**Issue by erlenmeyer316** [castlamp/zenbership#46]
When I select the "Fieldsets" menu item from the "Integrations" menu I get the following error:

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

This is a fresh install. I downloaded the zip from the 109_alpha branch at around 8:30 U.S central time tonight

I've attached a screenshot.

![screen shot 2017-03-30 at 8 47 54 pm](https://cloud.githubusercontent.com/assets/1102466/24533225/d4d740ac-158b-11e7-8228-929a1d8d7cb2.png)
. 

Thanks!

**Comment by jbelelieu** [comment]
You have strict mode on for your SQL server. You will need to turn that off or wait for a future version that is compatible with STRICT mode.
