### ISSUE TITLE
Send email using SMTP

### ISSUE THREAD

**Issue by ahsyaka** [castlamp/zenbership#47]
I have successfully installed Zenbership and everything works fine, except for email sending. My webhosting shutdown phpmail for security reasons, and they suggest me to use SMTP instead.

How to use SMTP in Zenbership?

Thanks in advance :)

**Comment by erlenmeyer316** [comment]
I have the same question. 

Thanks!

**Comment by jbelelieu** [comment]
Zenbership currently supports the use of the mail() function. If that doesn't work, it support the use of programmatic tools like mailgun (v109+) via plugins.

I'll do my best to get SMTP support added in future versions.
