### ISSUE TITLE
Upgrade or New Install

### ISSUE THREAD

**Issue by Th3Scorpio** [castlamp/zenbership#49]
Hi

Ive tried the upgrade path as in your documentation and brand new setup as well
When you run the setup all permissions is green, DB test fine
As soon you hit instaall the process.php sta blank
in error log I get the following
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS) in /admin/cp-classes/db.class.php on line 1

I get the same error when I install 107 and then upgrade to latest

**Comment by itworksjbo** [comment]
Make sure your server meets all [requirements](http://documentation.zenbership.com/Home/Server-Requirements). Refer to issue [#19](https://github.com/castlamp/zenbership/issues/19) for more info. Also you have to [disable](https://secure.php.net/manual/en/security.magicquotes.disabling.php) Magic Quotes.

**Comment by Th3Scorpio** [comment]
HI

Thank you for response
Another problem I have is the Currency

I’ve Selected ZAR but it default back to $

Regards

 André Esterhuizen
Phone:+27 11 412 2837 |Fax: +27 86 616 2747 | E-mail: andre@technowiz.co.za
"Nothing To Do With Magic, Everything To Do With Information Technology"
[Description: BBtr][Description: bbCA] [Description: MCSE-col.jpg]

**Comment by itworksjbo** [comment]
I assume then the initial problem is solved now? This issue thread should be closed then and a new one opened for the currency problem. This helps the developers to keep track of bugs.

**Comment by Th3Scorpio** [comment]
Thank you for very quick response. The problem were issue # 19 (https://github.com/castlamp/zenbership/issues/19)
Even making successful connection the STRICT_TRANS-TABLES caused the problem
