### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by Th3Scorpio** [castlamp/zenbership#50]
When ever I change the currency it does not reflect my currency.
If I go shop -> options->change the currency to ZAR it does not matter. it keep default back all over as $.
My regional settings and browser settings is also set to my Country codes and currency.
Ive done following changes in /admin/cp-classes/universal.class.php
(+- Line 370)
function currency_symbol($price)
{
    global $db;
    $currency = $db->get_option('currency');

    if ($currency == 'ZAR') {
        $final = 'R' . $price;
    }

still not working

any other place I can add to reflect through the software my currency

**Comment by itworksjbo** [comment]
Leave the change you made to /admin/cp-classes/universal.class.php and additionally add
else if ($cur == "ZAR") {
    define("CURRENCY_SYMBOL", "R");
    define("CURRENCY_SYMBOL_AFTER", "0");
    define("PRICE_FORMAT", "1");
}
to your /admin/sd-system/loader.php

**Comment by Th3Scorpio** [comment]
Aish..

THank you 

Actually forgot about the loader 
TX

**Comment by itworksjbo** [comment]
No problem mate 👍

**Comment by Th3Scorpio** [comment]
Hi

Im quite new to the software and have q view questions.

Is there a way to do a paid membership form, while the meber register, they receive a invoice but there status stay unpaid until manually processed. Don’t want to use credit card gateways.


Regards

 André Esterhuizen
Phone:+27 11 412 2837 |Fax: +27 86 616 2747 | E-mail: andre@technowiz.co.za
"Nothing To Do With Magic, Everything To Do With Information Technology"
[Description: BBtr][Description: bbCA] [Description: MCSE-col.jpg]

**Comment by itworksjbo** [comment]
Should be no problem. But I'm not too familiar with the software myself yet. I as well discovered it just a few days ago. So I can't really help you much on that regard. That would be a question for the developer or you'd have to do some digging yourself. Have a go with the [documentation](http://documentation.zenbership.com/) (haven't done that myself yet) or you could consider buying an [implementation](http://zenbership.com/Services/Installations-And-Implementations) if you're not willing to get down and dirty yourself. Hey, our friends over at castlamp want to make a living as well! :)

**Comment by Th3Scorpio** [comment]
Cool
Did some digging . Will have to do some custom dev.

**Comment by itworksjbo** [comment]
Hm too bad. :/ If you're right it might be a good feature request for
future development. Maybe open a new thread just in case, a dev might be
interested in what you have to say. And if you develop something
yourself be so kind file a pull request once it's done, will you? Me
myself and others might be interested in this as well. :)

**Comment by jbelelieu** [comment]
You can do that. Select no payment gateway, create the product, and add it to the registration form. When the user registers it will spawn an invoice which will appear on the member's "edit" screen in the admin backend (if you are using v109+) as an "unpaid" invoice. If you want to prevent the user from logging in until it is paid set the form up to "require admin approval" as the default status then update it once the invoice is settled to "active". Hope this helps!

**Comment by Th3Scorpio** [comment]
Hi

Thx for your response. Im actually on 107 but will go 109. Notixe there lot changes.
I did try you route in 107 , but soon the uaer check out , it mark the subscription as paid.

I created a custom hook in 107 to auto assign a member to specific cordinator for the club on regiatration, and i see that also might be in 109.

Will do the update and see what is on the table

Zenbershep is actually n very robust app it seems

I will def sup them.

Will keep you posted.

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Th3Scorpio** [comment]
Hi

To be clear, where do I select No Payment Gateway???
Im on v 109 now in windows.

If I crate product there is not an option for no payment gateway
All payment gateways is swithched off

I  Created subscription product
Created a paid form , added the product

As soon as I visit register page, it comes to point stating,
No primary payment gateway has been selected. Please select a payment gateway below:
No gateway list

As soon as I go and select shop==> setup==>payment gateways
And switch on one of the gateways it continue

It goes through the whole process.

When you login to Admin dashboard, it shows the subscription as invoices and already paid

So its back to drawing board



Regards

 André Esterhuizen
Phone:+27 11 412 2837 |Fax: +27 86 616 2747 | E-mail: andre@technowiz.co.za
"Nothing To Do With Magic, Everything To Do With Information Technology"
[Description: BBtr][Description: bbCA] [Description: MCSE-col.jpg]
