### ISSUE TITLE
zen109 Alpha Windows setup

### ISSUE THREAD

**Issue by Th3Scorpio** [castlamp/zenbership#52]
I decided to go and try install on windows. 
Pretty much for im constant on the road.
Im usin WAMP 2.06
PHP 5.6.25
MySQL 5.7
At first got Blank screen on setup.
Switched on error loging and it popup with this msg
) Fatal error: Call to undefined function installed_version() in C:\wamp64\www\zen109a\setup\process.php on line 37

Line 37: $version = installed_version();

**Comment by Th3Scorpio** [comment]
Forgot to say I used the index-win and process-win files
Changed the $version='110b'
It created the DB , confirmed it created the  config file, but actually did not.
It displayed the config file after setup.
The folder string were incorrect.
This is the format I changed it to:

<?php
define('PP_BASE_PATH','');
define('PP_PATH','C:\wamp64\www\zen109a\setup');
define('PP_URL','http://localhost/zen109a');
define('PP_ADMINPATH','C:\wamp64\www\zen109a\admin');
define('PP_ADMIN','http://localhost/zen109a/admin');
define('PP_PREFIX','ppSD_');
define('PP_MYSQL_HOST','localhost');
define('PP_MYSQL_DB','naspdb');
define('PP_MYSQL_USER','naspdb');
define('PP_MYSQL_PASS','P@ssword)1WiFi001');
define('ZEN_SECRET_PHRASE','');
define('ZEN_HIDE_DEBUG_TIME', false);
define('DISABLE_CAPTCHA', false);
define('DISABLE_PERFORMANCE_BOOSTS', false);
require PP_ADMINPATH . "/sd-system/loader.php";

got login screen and error again

'd4518d5966a749c7a33ec01ce50fa539', ?, ?, '2017-04-09 10:57:57', '2017-04-09 11:57:57', ?, '' )

Array
(
    [0] => HY000
    [1] => 1366
    [2] => Incorrect integer value: '' for column 'remember' at row 1
)


Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\wamp64\www\zen109a\admin\cp-classes\db.class.php on line 88
Call Stack
#	Time	       Memory	Function	Location
1	0.0027	256496	{main}( )	...\login.php:0
2	0.0842	2205208	admin->create_session( )	...\login.php:69
3	0.0850	2207464	db->insert( )	...\admin.class.php:2186
4	0.0913	2210760	db->error_process( )	...\db.class.php:90
5	0.0913	2212048	db->add_history( )	...\db.class.php:112
6	0.0914	2213464	db->insert( )	...\db.class.php:622
7	0.0915	2215936	execute ( )	...\db.class.php:88

**Comment by itworksjbo** [comment]
zenbership isn't really designed to run on Windows. Have a look at issue #7 though. Maybe that'll work. Or you could dualboot your computer into a slim Linux installation. Or use a virtual machine. Though last suggestion would drain the laptop battery. Btw why don't you just run it on a server and access it remote?

**Comment by itworksjbo** [comment]
Btw if you use windows 10 you probably could run in in their Ubuntu subsystem? https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/

**Comment by Th3Scorpio** [comment]
Hi

Gladd to say
Dumped WAMP, seems it could not handle the load
Installed XAMPP
With few tweeks

Im running latest stack on windows

**Comment by itworksjbo** [comment]
Great, good to hear :)
