### ISSUE TITLE
Member Management Menu improperly formatted in v111

### ISSUE THREAD

**Issue by jrehmer** [castlamp/zenbership#57]
I like the changes to the theme in v111, but the Membership Management Menu displayed on the site is improperly formatted.

![image](https://cloud.githubusercontent.com/assets/6783984/25065779/0bb934da-21db-11e7-9e4b-0566bff22884.png)

**Comment by jrehmer** [comment]
If I add "zen_menu_vertical zen_menu" to the Custom Class field when editing the menu in the admin panel it looks better.

![image](https://cloud.githubusercontent.com/assets/6783984/25065835/0af9458e-21dc-11e7-87c4-0d71b21299f8.png)

**Comment by jbelelieu** [comment]
The new versions request that the user specific a class for the navigation menus.

This is correct and has been updated since then.
