### ISSUE TITLE
Request Invoice option not given

### ISSUE THREAD

**Issue by jrehmer** [castlamp/zenbership#62]
We have Allow Invoicing set to yes as many of our members pay by check, and we have PayPal configured as a gateway.  When a user goes through the checkout process they are never given the option to invoice them, when they click checkout it takes them straight to PayPal.

**Comment by jrehmer** [comment]
I see that if I add a bunk credit card gateway as the Primary that the checkout process is much different.  When I do this I get directed to pp-cart/payment.php and there I have the three options (Credit Card, Paypal, Request Invoice).  Is there anyway if we're only planning to use PayPal that the option to invoice can still be presented during checkout?  Similar to #63 I don't see a good way to collect user information in the normal flow when PayPal is the only payment gateway.

**Comment by jbelelieu** [comment]
If you make PayPal your primary gateway, there is no way to allow the user to request an invoice unfortunately.
