### ISSUE TITLE
PayPal skips checkout steps resulting in no user information captured

### ISSUE THREAD

**Issue by jrehmer** [castlamp/zenbership#63]
When using PayPal as a gateway when a user adds a subscription product to their cart and clicks checkout they are directed to PayPal to complete the payment.  This results in no information being captured about the user.

We have a Paid Registration form that works great at capturing the member's contact information before it sends them to PayPal, but when a user simply adds the subscription product to the cart they don't go through the same registration process thus nothing is captured about the member during checkout.

**Comment by jbelelieu** [comment]
The correct flow for using PayPal in this case is scenario A. Scenario B is not supported for non-APIs.

**Comment by jrehmer** [comment]
I'm not sure I understand what you mean.  Basically if you use PayPal there is no way to capture member details such as e-mail, address, etc. unless you use a Paid Registration form?

**Comment by jbelelieu** [comment]
That is correct, yes. The program was designed to require paid registrations to go through a form. The option to auto-register users in the cart was added much later but will only work for API-based users.

**Comment by jrehmer** [comment]
We're a neighborhood association, and we have a paid registration form setup for membership dues, but we also have some neighborhood branded merchandise we'd like to sell.  Unfortunately with the lack of Payment Gateway options, PayPal is the only choice we're suited for using currently (we'd really love to see Square integration!).  We'd like to leave it open so that people don't have to register to purchase merchandise items, but it seems that I have no way to do this since no info is captured (no shipping information or any way to contact the person who made the purchase is captured).  Would the only solution be to have a dependency form assigned to the merchandise products?
