### ISSUE TITLE
No forms are displayed when multiple forms are publicly visible

### ISSUE THREAD

**Issue by jrehmer** [castlamp/zenbership#66]
When we have two or more forms set to Public Listing "yes" this is what the registration page looks like: 
![image](https://cloud.githubusercontent.com/assets/6783984/25309016/feb3af16-2786-11e7-848d-2dfe650a372f.png)

**Comment by erlenmeyer316** [comment]
Having the same issue

**Comment by jbelelieu** [comment]
What version of the program are you using?

**Comment by jrehmer** [comment]
Had the issue in v110, v111, and v112.  Currently running v112.

**Comment by jbelelieu** [comment]
Open register.php and change this line (line 84):

`'forms' => (! empty($get_forms['forms'])) ? $get_forms['forms'] : '',`

To this:

`'forms' => (! empty($get_forms['forms'])) ? $get_forms['list'] : '',`

**Comment by jrehmer** [comment]
On line 84 of register.php that I have contains:

`forms' => $get_forms['forms'],`

Should I still replace it with `'forms' => (! empty($get_forms['forms'])) ? $get_forms['list'] : '',`?

**Comment by jbelelieu** [comment]
Yes
