### ISSUE TITLE
Adding content on Zenbership

### ISSUE THREAD

**Issue by poqwsa** [castlamp/zenbership#67]
Can anyone help?
I have installed Zenbership and all seems to be working well. However, when I want to add content the required text/content field editor is missing. I can click on options and enter details there but I can't enter content.
It's the same with emails. I can enter information to the 'to' and subject fields but the content field is missing.

**Comment by jbelelieu** [comment]
Open sd-system/config.php and change the URLs to start with either "http://" or "https://" depending on where you installed it.

**Comment by poqwsa** [comment]
Thank you, worked a treat! Another small problem I'm having as follows: I create a product, upload the image, give it a description, physical product and price etc, etc. But, when I try to add to the cart from the live site the following pop up appears: 'You are only permitted to add unit(s) of this item into your cart'. Any ideas?

**Comment by jrehmer** [comment]
Did you set either the Max Per Cart or Minimum Per Cart options on the main screen of the product configuration?

**Comment by poqwsa** [comment]
yes, to start with and then removed any values. Both times the same message.

**Comment by poqwsa** [comment]
All sorted now.... I reopened my browser and it worked.. Thank you
