### ISSUE TITLE
Can't create an employee?

### ISSUE THREAD

**Issue by poqwsa** [castlamp/zenbership#70]
Hi

I click on create employee - ok
Give a job title - ok
Choose a department - ok
Choose permissions - ok
Phones cannot be edited
Username selection cannot be edited
Social media cannot be edited
No other option visible so not sure if anything else is missing.
After clicking save I get the following message:

Error!
The item that you are trying to view does not exist.

The result is no employee created and I'm back to the beginning.

Can you tell me what I need to change?

**Comment by monstermage** [comment]
I had the same issue. I found that not putting a middle name fixed the problem and was able to successfully save. Though having these errors so early in is making me very hesitant over continuing to use this software. My issue now is the CSS suddenly stopped showing up on the front end. Good luck on making a new employee, took me about 9 tries until no middle name fixed it.

**Comment by jbelelieu** [comment]
I appreciate you reporting this. I'm aware of the issues with the employee module. Starting in v115, the system will be changed completely. The program will consider all employees admins moving forward until a better permission system is in place.
