### ISSUE TITLE
v115 fresh install database error

### ISSUE THREAD

**Issue by m-nienberg** [castlamp/zenbership#82]
On a fresh install of v115, when the MySQL insert is run, it fails to create data for the table 'ppSD_fields'. There isn't any visible error and the program is unusable as a result. The problem is in the entry for the 'bank_name' field. The label_position field is blank and that causes the entire insert to fail. I changed it to 'left' and re-ran the insertion for the table. Now I am making some progress evaluating Zenbership.

**Comment by m-nienberg** [comment]
It's worse than I thought. There are a few other empty tables too. Examples: ppSD_note_labels, ppSD_options, ppSD_content, and more. Most of these are due to trying to insert empty strings where an integer is expected, or similar errors.

**Comment by jbelelieu** [comment]
I am aware of these issues and as-per the server requirements, you need to turn off MySQL strict mode for the time being to use the software.

**Comment by m-nienberg** [comment]
Thanks. For reference, this is MySQL version 5.6. For some reason I thought the STRICT problems were a result of the added restrictions on zero dates starting in 5.7. That was the case for other applications I am familiar with. The installation problem could be fixed by correcting the inserts.php file. Ideally you could test for MySQL version and STRICT as part of the install, but that is a feature request rather than a bug report.
